---
prometheus_version: "2.51.0"
prometheus_scrape_interval: 15s
prometheus_evaluation_interval: 15s
prometheus_retention_time: 15d
prometheus_storage_path: /var/lib/prometheus
prometheus_config_dir: /etc/prometheus
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_replica_label: a
