---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Reload prometheus
  ansible.builtin.uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    status_code: 200
